server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # - id: auth-service
        #   uri: lb://USER-SERVICE
        #   predicates:
        #     - Path=/auth-service/auth/**
        #   filters:
        #     - StripPrefix=1
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
        - id: table-management-service
          uri: lb://TABLE-MANAGEMENT-SERVICE
          predicates:
            - Path=/table-management-service/**
          filters:
            - StripPrefix=1
      # default-filters:
      # - DedupeResponseHeader=Access-Control-Allow-Origin
      # - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            exposed-headers: "X-Role"  # Izinkan header X-Role
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/